const types = new Map();
types.set("normal", __dirname + "../../../../assets/types/normal.png");
types.set("fire", __dirname + "../../../../assets/types/fire.png");
types.set("water", __dirname + "../../../../assets/types/water.png");
types.set("electric", __dirname + "../../../../assets/types/electric.png");
types.set("grass", __dirname + "../../../../assets/types/grass.png");
types.set("ice", __dirname + "../../../../assets/types/ice.png");
types.set("fighting", __dirname + "../../../../assets/types/fighting.png");
types.set("poison", __dirname + "../../../../assets/types/poison.png");
types.set("ground", __dirname + "../../../../assets/types/ground.png");
types.set("flying", __dirname + "../../../../assets/types/flying.png");
types.set("psychic", __dirname + "../../../../assets/types/psychic.png");
types.set("bug", __dirname + "../../../../assets/types/bug.png");
types.set("rock", __dirname + "../../../../assets/types/rock.png");
types.set("ghost", __dirname + "../../../../assets/types/ghost.png");
types.set("dragon", __dirname + "../../../../assets/types/dragon.png");
types.set("dark", __dirname + "../../../../assets/types/dark.png");
types.set("steel", __dirname + "../../../../assets/types/steel.png");
types.set("fairy", __dirname + "../../../../assets/types/fairy.png");

export { types };
